config/routes.rb
Rails.application.routes.draw do
  get "showcase" => "showcase#index"
  resources :entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  before_create :set_id

  private

  def set_id
    loop do
      self.id = SecureRandom.hex(4)
      break unless self.class.exists?(id: id)
    end
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  before_save :set_md5_checksum

  enum :status, { draft: "draft", published: "published" }

  def content_for_preview
    content.split("\n").first.gsub(/[#`\*_]/, "").strip
  end

  private

  def set_md5_checksum
    self.md5_checksum = Digest::MD5.hexdigest(content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
    fresh_when @entry
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    fresh_when @entry
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry, notice: "Entry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: "Entry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    redirect_to entries_path, status: :see_other, notice: "Entry was successfully destroyed."
  end

  private

  def set_entry
    @entry = Entry.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params.expect(entry: %i[title content])
  end
end

app/controllers/showcase_controller.rb
class ShowcaseController < ApplicationController
  def index
    @variants = %i[base primary secondary success danger]
    @sizes = %i[sm md lg]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/showcase_helper.rb
module ShowcaseHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id(entry) %>" class="mb-6">
  <h1 class="text-4xl font-black mb-4"><%= entry.title %></h1>
  
  <div 
    id="<%= dom_id entry %>"
    class="entry-display bg-white border-2 border-black p-4 border-brutal-radius">
    <%== marksmithed entry.content %>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, class: "contents") do |form| %>
  <% if entry.errors.any? %>
    <%= render Widgets::BrutalCardComponent.new(variant: :danger) do %>
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul class="list-disc ml-6">
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>

  <div class="mt-6">
    <%= form.label :title, class: "block text-sm font-semibold black uppercase" %>
    <div class="border-brutal-radius bg-black block">
      <%= form.text_field :title, class: "bg-white rounded-md px-4 py-3 border-2 border-black font-bold border-brutal-radius focus:outline-0 w-full mt-1 -translate-x-1 -translate-y-1 block" %>
    </div>
  </div>

  <div class="mt-6 border-brutal-radius block bg-black">
    <span class="block bg-white border-2 border-black border-brutal-radius -translate-x-1 -translate-y-2">
      <%= form.marksmith :content, class: "border-brutal-radius border-0", enable_file_uploads: false %>
    </span>
  </div>

  <div class="my-4">
    <%= render Widgets::ButtonComponent.new(text: "Save", type: "submit", variant: :primary) %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% content_for :title, "Editing entry" %>

<div class="w-full mx-auto">
  <div class="flex justify-between">
    <h1 class="font-bold text-4xl">Editing entry</h1>
    <div class="flex gap-x-4">
      <%= link_to @entry do %>
        <%= render Widgets::PlainButtonComponent.new do %>
          Show this entry
        <% end %>
      <% end %>
      <%= link_to entries_path do %>
        <%= render Widgets::PlainButtonComponent.new do %>
          Back to entries
        <% end %>
      <% end %>
    </div>
  </div>

  <%= render "form", entry: @entry %>

</div>

app/views/entries/index.html.erb
<% content_for :title, "Entries" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Entries</h1>

    <%= link_to new_entry_path do %>
      <%= render Widgets::ButtonComponent.new(text: "New Entry", variant: :primary) %>
    <% end %>
  </div>

  <div id="entries" class="min-w-full gap-y-4 flex flex-col mt-6">
    <% if @entries.any? %>
      <% @entries.each do |entry| %>
        <%= render Widgets::BrutalCardComponent.new do %>
          <h1 class="font-bold text-2xl"><%= entry.title %></h1>
          <p class="mt-2 mb-2 italic text-gray-800"><%= entry.content_for_preview %></p>
          <p>
            <%= link_to "Show this entry", entry, class: "py-1 font-semibold" %>
          </p>
        <% end %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No entries found.</p>
    <% end %>
  </div>
</div>

app/views/entries/new.html.erb
<% content_for :title, "New entry" %>

<div class="w-full mx-auto">
  <div class="flex justify-between">
    <h1 class="font-bold text-4xl mb-6">New entry</h1>
    <%= link_to entries_path do %>
      <%= render Widgets::PlainButtonComponent.new do %>
        Back to entries
      <% end %>
    <% end %>
  </div>

  <%= render "form", entry: @entry %>
</div>

app/views/entries/show.html.erb
<% content_for :title, @entry.title %>

<div class="mx-auto w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-4">
    <%= link_to entries_path do %>
      <%= render Widgets::PlainButtonComponent.new do %>
        <%= lucide_icon "chevron-left", class: "inline-block" %>
        <span>Back</span>
      <% end %>
    <% end %>
  </div>

  <%= render @entry %>

  <%= link_to edit_entry_path(@entry) do %>
    <%= render Widgets::ButtonComponent.new(text: "Edit") %>
  <% end %>
  <div class="inline-block ml-2">
    <%= button_to @entry, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } do %>
      <%= render Widgets::ButtonComponent.new(text: "Delete", variant: :danger) %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center text-sm text-gray-500 mt-10 py-4">
    hslzr &copy; All rights reserved.
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Journaling" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-refresh-method" content="morph">
    <meta name="turbo-refresh-scroll" content="preserve">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "marksmith" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-zinc-100">
    <main class="max-w-9/10 xl:max-w-5/10 md:max-w-8/10 mx-auto mt-16 xl:mt-28 px-5 flex min-h-[50vh]">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/showcase/index.html.erb
<div class="container mx-auto grid grid-cols-3 gap-4">
  <% @variants.each do |variant| %>
    <% @sizes.each do |size| %>
      <div>
        <%= render Widgets::ButtonComponent.new(variant: variant, size: size, text: "#{size} #{variant}") %>
      </div>
    <% end %>
  <% end %>
</div>